test_helper: fix flakiness with host IPs (timing issue)
Very rarely it happens that tap devices created by our test are not
recognized quickly enough by udev/networkd rules and get their
corresponding IPs assigned.

This refactors wait_for_ping() to also wait for the host to get the
IP address. I decided to do so as we typically call wait_for_ssh()
either after VM boot or after a network interface hotplug event,
which calls into `wait_for_ping()` then.

I also refactored the helpers to prevent spam. Using the new
code, a possible exception trace might look as follows:

(look for `192.168.5.1`)

```
Traceback (most recent call last):
  File "/nix/store/5givqzp19kdd1izq1rw54pl1hx8awv7k-python3.13-test_helper-0.1/lib/python3.13/site-packages/test_helper/test_helper.py", line 103, in wait_for_host_ip
    wait_until_succeed(check_ip, retries=20)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/5givqzp19kdd1izq1rw54pl1hx8awv7k-python3.13-test_helper-0.1/lib/python3.13/site-packages/test_helper/test_helper.py", line 64, in wait_until_succeed
    raise RuntimeError("function didn't succeed")
RuntimeError: function didn't succeed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 398, in test_hotplug
  File "/nix/store/5givqzp19kdd1izq1rw54pl1hx8awv7k-python3.13-test_helper-0.1/lib/python3.13/site-packages/test_helper/test_helper.py", line 154, in wait_for_ssh
    wait_for_host_ip(machine, ip)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/nix/store/5givqzp19kdd1izq1rw54pl1hx8awv7k-python3.13-test_helper-0.1/lib/python3.13/site-packages/test_helper/test_helper.py", line 108, in wait_for_host_ip
    raise RuntimeError(msg) from e
RuntimeError: Host doesn't has an IP in the same IPv4 network as 192.168.5.1
ip a:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    altname enx525400123456
    inet 10.0.2.15/24 metric 1024 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86367sec preferred_lft 86367sec
    inet6 fec0::7c6d:1f44:e1df:6d76/64 scope site temporary dynamic
       valid_lft 86369sec preferred_lft 14369sec
    inet6 fec0::5054:ff:fe12:3456/64 scope site dynamic mngtmpaddr noprefixroute
       valid_lft 86369sec preferred_lft 14369sec
    inet6 fe80::5054:ff:fe12:3456/64 scope link proto kernel_ll
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:12:01:02 brd ff:ff:ff:ff:ff:ff
    altname enp0s9
    altname ens9
    altname enx525400120102
    inet 192.168.100.1/24 brd 192.168.100.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe12:102/64 scope link proto kernel_ll
       valid_lft forever preferred_lft forever
4: br4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 4e:7c:29:70:81:6e brd ff:ff:ff:ff:ff:ff
5: br3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc htb state DOWN group default qlen 1000
    link/ether 52:54:00:a2:93:9d brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.1/24 brd 192.168.3.255 scope global br3
       valid_lft forever preferred_lft forever
```

On-behalf-of: SAP philipp.schuster@sap.com
Signed-off-by: Philipp Schuster <philipp.schuster@cyberus-technology.de>