testscript: wait_for_ssh() raises exception instead of returning bool
This is the first commit of a series intended to remove all old-school
`asserts` and replace them with more powerful exceptions.

While exception-based error handling can be considered controversial,
using exceptions in our test framework is the more effective approach.
It avoids the check-and-assert pattern and reduces assertion clutter.

Since we have no need to catch and handle errors, but just want to know
if something fails with maximum context, we retain the full benefits of
exceptions (most notably richer context and failure diagnostics) without
having to deal with the usual downsides at all.

Example (Before):
```
Traceback (most recent call last):
  File "<string>", line 269, in test_network_hotplug_persistent_vm_restart
AssertionError
```

Example (After):
```
Traceback (most recent call last):
  File "<string>", line 253, in test_network_hotplug_persistent_vm_restart
  File "<string>", line 1978, in wait_for_ssh
RuntimeError: Could not establish SSH connection to 192.168.1.2
```

## This Commit

Raise exceptions in wait_for_ssh(); no more old-school assert

On-behalf-of: SAP philipp.schuster@sap.com
Signed-off-by: Philipp Schuster <philipp.schuster@cyberus-technology.de>